using Xunit;

namespace InventoryManagement.EntityFrameworkCore;

[CollectionDefinition(InventoryManagementTestConsts.CollectionDefinitionName)]
public class InventoryManagementEntityFrameworkCoreCollection : ICollectionFixture<InventoryManagementEntityFrameworkCoreFixture>
{

}
